language: node_js
node_js:
- 7.7.1
after_script:
- scp -o StrictHostKeyChecking=no app.js root@59.110.243.215:/root/home
before_install:
- openssl aes-256-cbc -K $encrypted_047892bf4e9b_key -iv $encrypted_047892bf4e9b_iv
  -in id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh -f
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
